### PR TITLE
Various fixes for robustness and query accuracy

### PR DESCRIPTION
**Pull request by clegaspi**
Hi Conrad,

Thanks for putting this package together! It has helped me immensely to connect my work with the AFLOW database. In the course of using your package to query the database, I ran into some issues and I thought I would submit a PR to update the code according to the issues that I found.

_The keyword 'ael_elastic_anistropy' fails_
The key is misspelled. Fixed the misspelling throughout the code base.

_Other keywords cause query failure_
These keys (author, Pullay stress, etc.) appear to have been removed from the API. They have been removed from the code base.

_Specifying 'catalog' as a selected keyword fails_
AFLUX doesn't support using catalog as a keyword to query, only as a filter. Removed it from the keyword list, but retained it as an `Entry` property because it can be retrieved from the aurl JSON.

_caster does not handle some 'kpoints' entries correctly_
Some kpoints entries only have one set of parameters, the relaxed one. Updated to accommodate.

_caster does not handle 'ldau_TLUJ' parameters correctly_
Created custom casting type as a dict.

_The filter operators < and > do not match the specifications of the AFLUX API_
As currently implemented, < and > actually generate a URI which queries the database with <= and >=, respectively. Updated the overloaded operators for Keyword to reflect the specifications in the AFLUX API, adding < and > and also support for != as a bonus. String comparisons still use < and > and cannot use <= and >=.

_The inversion filter operator did not always invert correctly_
The inversion usually failed when there were multiple filters where some were already inverted and others were not. Updated to more robustly handle inversion with multiple filters.

_The entry tests are failing!_
There were some deprecated materials being referenced, so I changed them out arbitrarily for some that were still in the database. You might want to regenerate the JSON files to have fresh database material.

_orderby() causes the keyword to be repeated if it's used as a filter, exclude, select_
Not an easy way around it, but we can save characters by just populating the name or "$"+name for excluded keywords at the beginning of the URI. Updated code to remove the keyword from self.selects (and self.excludes) because the use of `(kw) in self.selects` does not work because the == operator is overloaded.

_When I submit a query that succeeds but returns nothing, I get a weird error about a list not having keys_
This situation is now caught and addressed with a more helpful error message.

I also updated the tests to reflect the new changes and added more tests for the filter operators. I know this is kind of a lot addressed by one PR, but I hope these changes are acceptable to you! I ran the tests under Python 3.6 and 2.7, but I'd run them again just to make sure.

One thing I wasn't able to address was that complex filters, especially mixing `and` and `or` (e.g. `(Egap>1 & PV_cell>5) | (Egap<1 & PV_cell<1)`) seem to not retrieve the correct data, which, I think, is a bug/shortcoming in the AFLUX API (or my understanding of its syntax) and not in your code.

Let me know if you have questions or suggestions as to how I could do better. This is my first big PR for a repository that's not mine.

### CODE REVIEW

**Comment by clegaspi** [comment]
I will check the coveralls to add coverage!

**Comment by clegaspi** [comment]
Ok, I think I'm done making changes (sorry for all the extra commits). The decreased coverage seems to be in the utilities section which has to do with a python 2/3 difference, which is present in master.

**Comment by rosenbrockc** [comment]
Dear Christian,

thank-you for all this work. It looks great! Don't worry about the coverage, I only pay attention to the `python3` coverage because of `six.PY2` logical separations at various points. I'll merge it in.

**Comment by clegaspi** [comment]
Cool, thank you! Will you please also update it on pypi when you get a chance so I can pull it in to my package? Thank you!

**Comment by rosenbrockc** [comment]
Done. The pypi version should match now. Thank-you for your help!

**Pull request merged**
